server {
    # Railway menjalankan aplikasi pada port 8080
    listen 8080;
    
    # Menentukan folder root ke /app/public (lokasi file index.php Laravel)
    root /app/public;
    index index.php;
    
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Konfigurasi agar file .php bisa dijalankan oleh server
    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}